services:
  api:
    build: .
    container_name: project-manager-api
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: sh -c "npm run migration:run && npm run start:prod"
    volumes:
      - .:/api
      - /api/node_modules
